import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import ShinyBackground from '@/components/ShinyBackground'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='de'>
      <body
        className={clsx(
          inter.variable,
          'bg-background text-foreground font-inter',
        )}
      >
        {children}
        <ShinyBackground />
        <footer className='text-accent'>
          &apos;Animated Flying Fluttering Butterfly Loop&apos; (https://skfb.ly/o9Bsw) by
          LasquetiSpice is licensed under Creative Commons Attribution
          (http://creativecommons.org/licenses/by/4.0/).
        </footer>
      </body>
    </html>
  )
}
